### ISSUE TITLE
USER STORY: Publish running dates based on poll results

### ISSUE THREAD

**Issue by MariaHochstoeger** [MariaHochstoeger/agile-project1#5]
As a **site admin** I can **publish the next running dates based on the poll results** so that **they are visible to site visitors**

### Acceptance Criteria:
- There is a button next to the poll result which lets me publish the next running date
- I can choose which of the results get published as a running date

### Tasks:
- [ ] Add a button next to the poll results to publish next running dates
- [ ] Create html and css to display the next running dates
- [ ] Create tick boxes next to poll results to choose which results get pushed into the next running dates section
- [ ] Test functionality
